### ISSUE TITLE
Add benchmarking library

### ISSUE THREAD

**Issue by jemc** [savi-lang/savi#121]
Savi is focused helping you write high-performance programs, so it seems clear that we need good benchmarking tooling.

Suggestion is to have a similar implementation to [Pony's benchmark library](https://stdlib.ponylang.io/ponybench--index) and maybe copy some of the features/ergonomics of Rust's benchmarking tooling.

**Comment by mneumann** [comment]
Closing, as there is https://github.com/savi-lang/Benchmark
