### ISSUE TITLE
Add throwing numerical conversion methods (e.g. `u32!`)

### ISSUE THREAD

**Issue by mneumann** [savi-lang/savi#212]
Trait `Numeric` has various conversion methods between numerical integer types, but they are rather unsafe as they don't range-check. For instance `USize[256].u8` would most likely result in `0`.

Add "safe" counterparts:

```savi
:trait val Numeric
  :fun u8! U8
  :fun u32! U32
  :fun u64! U64
  // ...
```

and implementations like this:

```savi
:numeric U32
  :fun u8! U8
    if (@ < 256) (@ | error!)
```

Or wait until we get generic methods and make use of `min_value` and `max_value`.

**Comment by jemc** [comment]
I'm in the midst of revamping some stuff in `Numeric.savi` and adding lots of documentation.

So I can add these methods as well, while I'm at it.

**Comment by mneumann** [comment]
@jemc Go for it! :D
