### ISSUE TITLE
Add `native_to_network` as an alias to `native_to_be`

### ISSUE THREAD

**Issue by mneumann** [savi-lang/savi#349]
While `*_to_be` and `*_to_le` are pretty easy to type, it can sometimes be hard to remember what again was Big or Little endian. And in most cases, we want to convert from native to network byte order as certain formats are defined in network byte order.

**Comment by jemc** [comment]
I suppose this is reasonable. Want to do a PR for it?

**Comment by mneumann** [comment]
Implemented by PR #352
