### ISSUE TITLE
Add `Integer.Format.ASCII` to format `U8`... as ASCII character(s)

### ISSUE THREAD

**Issue by mneumann** [savi-lang/savi#350]
Ideally, we'd have a separate `Char` or `Rune` type.

Use case: Display Postgres frame types, e.g. 'F' as 'F' and not as 70.

```savi
frame_type U8 = 'F'
env.out.print("Frame type \( frame_type.format.ascii )")
```

**Comment by jemc** [comment]
Maybe we should go further and make it able to format Unicode codepoints beyond the ASCII range as well?

(and thus name it something like `.format.unicode` instead of `.format.ascii`)
