### ISSUE TITLE
No nice error for parameter with no parameter name.

### ISSUE THREAD

**Issue by mneumann** [savi-lang/savi#439]
```
Unhandled exception: Not Implemented: [:qualify, [:ident, "CPointer"], [:group, "(", [:ident, "F64"]]] (NotImplementedError)
  from /tmp/cirrus-ci-build/src/savi/ast/extract.cr:26:7 in 'param'
  from /tmp/cirrus-ci-build/src/savi/compiler/refer.cr:168:15 in 'run'
  from /tmp/cirrus-ci-build/src/savi/compiler/context.cr:147:7 in 'satisfy'
  from /tmp/cirrus-ci-build/src/savi/compiler.cr:313:5 in 'compile'
  from /tmp/cirrus-ci-build/src/savi/compiler.cr:247:25 in 'compile'
  from /tmp/cirrus-ci-build/main.cr:345:9 in 'run'
  from /tmp/cirrus-ci-build/src/savi/compiler.cr:12:5 in '->'
  from /tmp/cirrus-ci-build/main.cr:153:3 in 'start'
  from /tmp/cirrus-ci-build/main.cr:449:1 in '__crystal_main'
  from /usr/local/lib/crystal/crystal/main.cr:115:5 in 'main'
```

**Comment by jemc** [comment]
More context is needed to reproduce your issue - can you please share a full code example that crashes?

`CPointer(F64)` in and of itself has no issue, both as a type annotation and as a call receiver, as demonstrated by this example:

```sh
savi eval 'ptr CPointer(F64) = CPointer(F64).null, env.out.print("\(ptr.address)")'
# prints `0`, as expected
```

So there's something about the surrounding context for how you're using the `CPointer(F64)` expression that triggers the compiler fault. Seeing a full code example that crashes will help to reproduce.

**Comment by mneumann** [comment]
It's a FFI declaration like this:

```
:ffi glfwGetCursorPos(window CPointer(_FFI.Window.Opaque), CPointer(F64), CPointer(F64)) None
```

**Comment by mneumann** [comment]
There must be something wrong in `Savi::AST::Extract.name_and_params`. Dunno why the `AST::Qualify` case does not match...

**Comment by jemc** [comment]
If you share a code sample that triggers the fault we can diagnose.

**Comment by mneumann** [comment]
There we go:

```savi
// Main.savi
:module _FFI
  :ffi foobar(CPointer(F64)) None

:actor Main
  :new (env Env)
    env.out.print("Hello, World!")
```

**Comment by jemc** [comment]
Okay, the issue here is that the parameter name is required. So rather than just:
```savi
  :ffi foobar(CPointer(F64)) None
```

It should be:
```savi
  :ffi foobar(some_name CPointer(F64)) None
```

So to resolve this ticket I need to add a nice error message that tells you how to fix it, and add a test case to exercise the new error message.

**Comment by mneumann** [comment]
Ahhh, I feel super stupid to overlook this. It happened more than once. Thanks for pointing out!
