### ISSUE TITLE
macOS 13 required for savi on macOS?

### ISSUE THREAD

**Issue by achou11** [savi-lang/savi#454]
Installed the latest Savi via asdf today (https://github.com/savi-lang/savi/releases/tag/v0.20230324.0) and get this error when running `savi`:

```sh
dyld: Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /Users/andrewchou/.asdf/installs/savi/0.20230324.0/bin/savi (which was built for Mac OS X 13.0)
  Expected in: /usr/lib/libc++.1.dylib

Abort trap: 6
```

I'm on macOS 11 and wasn't planning to upgrade anytime soon. Guessing this is just a matter of not being able to use a prebuilt version of Savi at this point. Maybe worth documenting for macOS users :)

**Comment by achou11** [comment]
hm now i'm wondering if this is actual issue with my machine. getting the same error message for as far back as https://github.com/savi-lang/savi/releases/tag/v0.20230130.0 (pretty sure i had one of the february releases installed and working prior to attempting to upgrade to latest). guess this is now a matter of figuring out what's going on with my machine - help appreciated 😄

**Comment by achou11** [comment]
yeah that's certainly out of the range of my knowledge, although this flag seems be relevant?

https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-mmacos-version-min

otherwise, not requesting for you to go out of your way to support older versions if there's no straightforward way of doing so - just adding a note about supported versions would be helpful

**Comment by jemc** [comment]
@achou11 Please check https://github.com/savi-lang/savi/releases/tag/v0.20230405.0 after the build completes to see if the issue persists, and close this ticket if it's working for you now.

**Comment by achou11** [comment]
unfortunately still seeing the same issue :/

**Comment by achou11** [comment]
Upgraded my machine to the latest macOS, so can no longer confirm if this issue is still relevant. Closing as a result :)
